### ISSUE TITLE
ACF call to acf_get_fields_by_id is now depricated

### ISSUE THREAD

**Issue by Milner99** [dream-encode/de-acf-post-object-addon#1]
Hi,

We use this plugin and it requires an update. 

**Details**:
`acf_get_fields_by_id is deprecated since version 5.7.11! Use acf_get_fields() instead. in .../wp-includes/functions.php on line 3888`

**ACF Documentation**:
https://www.advancedcustomfields.com/resources/get_fields/

Kind Regards

Milner99

**Comment by dream-encode** [comment]
@Milner99

Thanks for reporting.  I'm pushing an updated version to the WordPress Plugin Repository now.  

For reference, this repo is currently out of date.  I'll be refreshing the code with v1.1.4 shortly.

**Comment by Milner99** [comment]
Magic. Thanks for a quick turnaround.
